### ISSUE TITLE
Importing library projects

### ISSUE THREAD

**Issue by todipratik** [archrival/Subsonic-Android#10]
@archrival How to import the library projects (pulltorefresh, menudrawer, drag-sort-listview) in the parent app (UltraSonic)?

**Comment by todipratik** [comment]
I am using Eclipse.

**Comment by tthomas48** [comment]
They're submodules:

git submodule update --init --recursive

I've actually change this to use gradle so you can use AndroidStudio
in my spotify branch. This isn't probably code you want to use, but
you might be able to pull out the relevant build stuff:

https://github.com/tthomas48/Subsonic-Android/tree/spotify

Thanks,

Tim Thomas

**Comment by todipratik** [comment]
Thanks
